import { PortfolioItem } from "@/types";

export const portfolioItems: PortfolioItem[] = [
  {
    id: "amalfi-coast-nuptials",
    title: "The Amalfi Coast Nuptials",
    category: "Destination Weddings",
    location: "Villa Cimbrone, Ravello, Italy",
    date: "June 2025",
    description:
      "A cliffside celebration perched above the Mediterranean, featuring cascading white florals, classical strings, and an intimate candlelit cliff terrace banquet.",
    coverImage: "/images/portfolio/amalfi-wedding.jpg",
    images: [
      "/images/portfolio/amalfi-wedding.jpg",
      "/images/hero/68f7a9ec2594c90df320fd2e_moment_01.avif",
      "/images/hero/6a6305bf5040b777232a1817_post-one-multy-image-one.avif",
      "/images/hero/68f7a9ec00af763bac20fb90_moment_02.avif",
      "/images/hero/6a6305bf5040b777232a1832_post-one-multy-image-two.avif",
      "/images/hero/6a6305bf5040b777232a15c2_Gallery-image.avif",
    ],
    featured: true,
  },
  {
    id: "chateau-chantilly-gala",
    title: "Château de Chantilly Grandeur",
    category: "Luxury Weddings",
    location: "Chantilly, France",
    date: "September 2025",
    description:
      "An opulent 18th-century French chateau wedding with gilded accents, crystal chandeliers, a bespoke champagne tower, and a midnight fireworks display.",
    coverImage: "/images/portfolio/chateau-wedding.jpg",
    images: [
      "/images/portfolio/chateau-wedding.jpg",
      "/images/hero/68f4fee8bf77d1636d385647_Service_02.avif",
      "/images/hero/6a6305bf5040b777232a15ee_Vision-home-two-image.avif",
      "/images/hero/6a6305bf5040b777232a182d_post-two-multy-image-one.avif",
      "/images/hero/6a6305bf5040b777232a183c_post-two-venue-details-image-three.avif",
      "/images/hero/68f7a9ec75ddeef8288c6569_moment_03.avif",
    ],
    featured: true,
  },
  {
    id: "cotswolds-celebration",
    title: "Cotswolds Countryside Romance",
    category: "Bespoke Celebrations",
    location: "The Cotswolds, United Kingdom",
    date: "May 2025",
    description:
      "An organic, meadow-inspired garden marquee wedding celebrating British countryside charm with wild English roses and bespoke artisan dining.",
    coverImage: "/images/portfolio/cotswolds-wedding.jpg",
    images: [
      "/images/portfolio/cotswolds-wedding.jpg",
      "/images/hero/6a6305bf5040b777232a1833_post-one-multy-image-three.avif",
      "/images/hero/6a6305bf5040b777232a183b_post-one-multy-image-four.avif",
      "/images/hero/68f7a9ec0ff41c408c8ccca4_moment_06.avif",
      "/images/hero/6a6305bf5040b777232a15f1_Vision-home-two-image.avif",
      "/images/hero/6a6305bf5040b777232a1846_post-four-multy-image-one.avif",
    ],
    featured: true,
  },
  {
    id: "lake-como-waterfront-soiree",
    title: "Lake Como Waterfront Soirée",
    category: "Destination Weddings",
    location: "Villa Balbiano, Lake Como, Italy",
    date: "July 2025",
    description:
      "Arrival by vintage wooden speedboats, velvet lounges on manicured lawns, and an ethereal glasshouse dinner beneath cascading wisteria.",
    coverImage: "/images/portfolio/lake-como-wedding.jpg",
    images: [
      "/images/portfolio/lake-como-wedding.jpg",
      "/images/hero/6a6305bf5040b777232a15c2_Gallery-image.avif",
      "/images/hero-couple.jpg",
      "/images/hero/68f7a9ec00af763bac20fb90_moment_02.avif",
      "/images/hero/6a6305bf5040b777232a1817_post-one-multy-image-one.avif",
      "/images/hero/6a6305bf5040b777232a183c_post-two-venue-details-image-three.avif",
    ],
    featured: true,
  },
  {
    id: "kyoto-garden-ceremony",
    title: "Kyoto Heritage Sanctuary",
    category: "Destination Weddings",
    location: "Kyoto, Japan",
    date: "October 2025",
    description:
      "A harmonious blend of Japanese architectural serenity and contemporary elegance, framed by autumn maple foliage and minimalist floral sculptures.",
    coverImage: "/images/portfolio/kyoto-wedding.jpg",
    images: [
      "/images/portfolio/kyoto-wedding.jpg",
      "/images/hero/68f7a9ec2594c90df320fd2e_moment_01.avif",
      "/images/about-hero.jpg",
      "/images/hero/6a6305bf5040b777232a1832_post-one-multy-image-two.avif",
      "/images/hero/6a6305bf5040b777232a15ee_Vision-home-two-image.avif",
      "/images/hero/68f7a9ec75ddeef8288c6569_moment_03.avif",
    ],
    featured: false,
  },
  {
    id: "manhattan-rooftop-gala",
    title: "Manhattan Skyline Gala",
    category: "Editorial & Galas",
    location: "Tribeca, New York City",
    date: "December 2025",
    description:
      "A sleek, black-tie milestone gala overlooking the glittering New York skyline with dramatic monochromatic styling and bespoke jazz performances.",
    coverImage: "/images/portfolio/manhattan-gala.jpg",
    images: [
      "/images/portfolio/manhattan-gala.jpg",
      "/images/hero/68f4fee8bf77d1636d385647_Service_02.avif",
      "/images/hero/6a6305bf5040b777232a1846_post-four-multy-image-one.avif",
      "/images/hero/68f7a9ec0ff41c408c8ccca4_moment_06.avif",
      "/images/hero/6a6305bf5040b777232a182d_post-two-multy-image-one.avif",
      "/images/hero/6a6305bf5040b777232a183b_post-one-multy-image-four.avif",
    ],
    featured: false,
  },
];
